services:
  persondb:
    container_name: persondb
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
